name: Auto-Deploy

on:
  push:
    branches: [ master, develop ]

jobs:
  deploy:
    name: Auto Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Preview
        if: github.ref == 'refs/heads/develop'
        uses: appleboy/ssh-action@master
        env:
          DB_NAME: database_name_preview
        with:
          host: seguemedia.com
          username: bstanley
          key: ${{ secrets.SANDBOX_SSH_KEY }}
          passphrase: ${{ secrets.SANDBOX_SSH_PASSWORD }}
          port: 2222
          use_insecure_cipher: true
          script: |
            cd /home3/bstanley/preview.seguemedia.com
            git checkout develop
            git pull
            git status
      
      - name: Deploy to Production
        if: github.ref == 'refs/heads/master'
        uses: appleboy/ssh-action@master
        env:
          DB_NAME: database_name_production
        with:
          host: seguemedia.com
          username: bstanley
          key: ${{ secrets.SANDBOX_SSH_KEY }}
          passphrase: ${{ secrets.SANDBOX_SSH_PASSWORD }}
          port: 2222
          use_insecure_cipher: true
          script: |
            cd /home3/bstanley/prod.seguemedia.com
            git checkout master
            git pull
            git status
