name: Auto-Deploy

on:
  push:
    branches: [ main, develop ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Preview Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 192.254.190.128
          username: bstanley
          key: ${{ secrets.SANDBOX_SSH_KEY }}
          port: 2222
          script: |
            cd /home3/bstanley/preview.seguemedia.com
            git pull origin master
            git status
